### ISSUE TITLE
Segmentation fault - HTTP - POST - gzip pcompression /gzip compression and chunked encoding

### ISSUE THREAD

**Issue by 2xyo** [Cisco-Talos/file2pcap#4]
POST HTTP gzip compression segmentation fault :
```console
$ wget http://www.eicar.org/download/eicar.com.txt
$ file eicar.com.txt
eicar.com.txt: EICAR virus test files
$ ./file2pcap --srcip 1.1.1.1 --dstip 2.2.2.2 -mH --http-encoder 1 eicar.com.txt
Writing to eicar.com.txt-http-post.pcap
Fatal error: glibc detected an invalid stdio handle
Aborted
$ sudo tcpdump -A -n -q -r eicar.com.txt-http-post.pcap 
reading from file eicar.com.txt-http-post.pcap, link-type EN10MB (Ethernet)
14:55:36.013000 IP 1.1.1.1.10280 > 2.2.2.2.80: tcp 0
E..(<...@.7.........((.P...0....P...je..
14:55:36.026000 IP 2.2.2.2.80 > 1.1.1.1.10280: tcp 0
E..(....@............P((...g...1P...i...
14:55:36.039000 IP 1.1.1.1.10280 > 2.2.2.2.80: tcp 0
E..('~..@.MM........((.P...1...hP...i...
14:55:36.052000 IP 1.1.1.1.10280 > 2.2.2.2.80: tcp 697
E.......@..\........((.P...1...hP...JY..POST /file2pcap.cgi HTTP/1.1
Host: wrl
User-Agent: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.17) Gecko/20081007 Firefox/2.0.0.17
Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
Accept-Language: en-us,en;q=0.5
Content-Length: 303
Content-Type: multipart/form-data; boundary=---------------------------8173728711543081858379436204
Accept-Encoding: gzip,deflate
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Keep-Alive: 300
Connection: keep-alive

-----------------------------8173728711543081858379436204
Content-Disposition: form-data; name="file"; filename="eicar.com.txt"
Content-Type: application/octet-stream


14:55:36.065000 IP 2.2.2.2.80 > 1.1.1.1.10280: tcp 0
E..(Z8..@............P((...h....P...g5..


$ rm eicar.com.txt-http-post.pcap
$ gdb -ex=r -ex=bt -ex=c -ex=quit --args ./file2pcap --srcip 1.1.1.1 --dstip 2.2.2.2 -mH --http-encoder 1 eicar.com.txt
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
<...redacted...>
Reading symbols from ./file2pcap...done.
Starting program: /home/yo/file2pcap/file2pcap --srcip 1.1.1.1 --dstip 2.2.2.2 -mH --http-encoder 1 eicar.com.txt
Writing to eicar.com.txt-http-post.pcap
Fatal error: glibc detected an invalid stdio handle

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7bf7535 in __GI_abort () at abort.c:79
#2  0x00007ffff7c4e508 in __libc_message (action=action@entry=(do_abort | do_backtrace), fmt=fmt@entry=0x7ffff7d58e89 "%s") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff7c4e532 in __GI___libc_fatal (message=message@entry=0x7ffff7d5aad0 "Fatal error: glibc detected an invalid stdio handle\n") at ../sysdeps/posix/libc_fatal.c:191
#4  0x00007ffff7c4ed57 in _IO_vtable_check () at vtables.c:72
#5  0x00007ffff7c46b91 in IO_validate_vtable (vtable=0x55555555634a <_start+42>) at ../libio/libioP.h:838
#6  _IO_seekoff_unlocked (fp=0x7fffffffdcf0, offset=0, dir=<optimized out>, mode=<optimized out>) at ioseekoff.c:59
#7  0x00007ffff7c4d304 in __GI_rewind (fp=0x7fffffffdcf0) at rewind.c:35
#8  0x000055555555ab97 in httpTransferFile (ho=0x7fffffffd560) at http.c:198
#9  0x0000555555558187 in httpPost (ho=0x7fffffffd560) at file2pcap.c:828
#10 0x0000555555558fe0 in main (argc=9, argv=0x7fffffffdde8) at file2pcap.c:1286
Continuing.

Program terminated with signal SIGABRT, Aborted.
The program no longer exists.

```
Same with POST HTTP gzip compression and chunked encoding : 

```console
$ rm eicar.com.txt-http-post.pcap
$ ./file2pcap --srcip 1.1.1.1 --dstip 2.2.2.2 -mH --http-encoder 3 eicar.com.txt
Writing to eicar.com.txt-http-post.pcap
Segmentation fault

$ sudo tcpdump -A -n -q -r eicar.com.txt-http-post.pcap reading from file eicar.com.txt-http-post.pcap, link-type EN10MB (Ethernet)
14:55:36.013000 IP 1.1.1.1.29sudo tcpdump -A -n -q -r eicar.com.txt-http-post.pcap 683 > 2.2.2.2.80: tcp 0
E..(.
..@...........s..P...L....P....~..
14:55:36.026000 IP 2.2.2.2.80 > 1.1.1.1.29683: tcp 0
E..(....@............Ps...	....MP.......
14:55:36.039000 IP 1.1.1.1.29683 > 2.2.2.2.80: tcp 0
E..(....@..#........s..P...M..	.P.......
14:55:36.052000 IP 1.1.1.1.29683 > 2.2.2.2.80: tcp 697
E.......@.e ........s..P...M..	.P....=..POST /file2pcap.cgi HTTP/1.1
Host: wrl
User-Agent: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1.17) Gecko/20081007 Firefox/2.0.0.17
Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5
Accept-Language: en-us,en;q=0.5
Content-Length: 303
Content-Type: multipart/form-data; boundary=---------------------------8173728711543081858379436204
Accept-Encoding: gzip,deflate
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Keep-Alive: 300
Connection: keep-alive

-----------------------------8173728711543081858379436204
Content-Disposition: form-data; name="file"; filename="eicar.com.txt"
Content-Type: application/octet-stream


14:55:36.065000 IP 2.2.2.2.80 > 1.1.1.1.29683: tcp 0
E..(s...@............Ps...	.....P.......

$ gdb -ex=r -ex=bt -ex=c -ex=quit --args ./file2pcap --srcip 1.1.1.1 --dstip 2.2.2.2 -mH --http-encoder 3 eicar.com.txt
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
<...redacted>
Reading symbols from ./file2pcap...done.
Starting program: /home/yo/file2pcap/file2pcap --srcip 1.1.1.1 --dstip 2.2.2.2 -mH --http-encoder 3 eicar.com.txt
Writing to eicar.com.txt-http-post.pcap
Fatal error: glibc detected an invalid stdio handle

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7bf7535 in __GI_abort () at abort.c:79
#2  0x00007ffff7c4e508 in __libc_message (action=action@entry=(do_abort | do_backtrace), fmt=fmt@entry=0x7ffff7d58e89 "%s") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff7c4e532 in __GI___libc_fatal (message=message@entry=0x7ffff7d5aad0 "Fatal error: glibc detected an invalid stdio handle\n") at ../sysdeps/posix/libc_fatal.c:191
#4  0x00007ffff7c4ed57 in _IO_vtable_check () at vtables.c:72
#5  0x00007ffff7c46b91 in IO_validate_vtable (vtable=0x55555555634a <_start+42>) at ../libio/libioP.h:838
#6  _IO_seekoff_unlocked (fp=0x7fffffffdcf0, offset=0, dir=<optimized out>, mode=<optimized out>) at ioseekoff.c:59
#7  0x00007ffff7c4d304 in __GI_rewind (fp=0x7fffffffdcf0) at rewind.c:35
#8  0x000055555555ab97 in httpTransferFile (ho=0x7fffffffd560) at http.c:198
#9  0x0000555555558187 in httpPost (ho=0x7fffffffd560) at file2pcap.c:828
#10 0x0000555555558fe0 in main (argc=9, argv=0x7fffffffdde8) at file2pcap.c:1286
Continuing.

Program terminated with signal SIGABRT, Aborted.
The program no longer exists.

```

`file2pcap` compiled with `-g3 -Wall -Wextra`with gcc version 8.3.0 on Debian 10.

**Comment by Talos-Martin** [comment]
"Fixed" in 1.30. Disallowed non-default encoding for HTTP Post.
